require 'dry-initializer'
require 'dry-types'
require 'voxable-api-ai-ruby'
require 'colorize'
require 'awesome_print'

# TODO: http://api.rubyonrails.org/classes/ActiveSupport/Autoload.html
require 'expando/version'
require 'expando/types'
require 'expando/logger'
require 'expando/expander'
require 'expando/project_template'
require 'expando/tokens'
require 'expando/source_files/base'
require 'expando/source_files/intent_file'
require 'expando/source_files/entity_file'
require 'expando/source_files/responses_file'
require 'expando/api_ai/system_entity_examples'
require 'expando/api_ai/objects/base'
require 'expando/api_ai/objects/intent'
require 'expando/api_ai/objects/entity'
require 'expando/api_ai/updaters/base'
require 'expando/api_ai/updaters/entity_updater'
require 'expando/api_ai/updaters/intent_updater'

module Expando; end
